export const useCity = () => {
  const cityArea = ref([
    /*直轄市*/
    {
      city: "台北市",
      areas: [
        { area: "中正區", zipcode: "100" },
        { area: "大同區", zipcode: "103" },
        { area: "中山區", zipcode: "104" },
        { area: "松山區", zipcode: "105" },
        { area: "大安區", zipcode: "106" },
        { area: "萬華區", zipcode: "108" },
        { area: "信義區", zipcode: "110" },
        { area: "士林區", zipcode: "111" },
        { area: "北投區", zipcode: "112" },
        { area: "內湖區", zipcode: "114" },
        { area: "南港區", zipcode: "115" },
        { area: "文山區", zipcode: "116" },
      ],
    },
    {
      city: "新北市",
      areas: [
        { area: "萬里區", zipcode: "207" },
        { area: "金山區", zipcode: "208" },
        { area: "板橋區", zipcode: "220" },
        { area: "汐止區", zipcode: "221" },
        { area: "深坑區", zipcode: "222" },
        { area: "石碇區", zipcode: "223" },
        { area: "瑞芳區", zipcode: "224" },
        { area: "平溪區", zipcode: "226" },
        { area: "雙溪區", zipcode: "227" },
        { area: "貢寮區", zipcode: "228" },
        { area: "新店區", zipcode: "231" },
        { area: "坪林區", zipcode: "232" },
        { area: "烏來區", zipcode: "233" },
        { area: "永和區", zipcode: "234" },
        { area: "中和區", zipcode: "235" },
        { area: "土城區", zipcode: "236" },
        { area: "三峽區", zipcode: "237" },
        { area: "樹林區", zipcode: "238" },
        { area: "鶯歌區", zipcode: "239" },
        { area: "三重區", zipcode: "241" },
        { area: "新莊區", zipcode: "242" },
        { area: "泰山區", zipcode: "243" },
        { area: "林口區", zipcode: "244" },
        { area: "蘆洲區", zipcode: "247" },
        { area: "五股區", zipcode: "248" },
        { area: "八里區", zipcode: "249" },
        { area: "淡水區", zipcode: "251" },
        { area: "三芝區", zipcode: "252" },
        { area: "石門區", zipcode: "253" },
      ],
    },
    {
      city: "桃園市",
      areas: [
        { area: "中壢區", zipcode: "320" },
        { area: "平鎮區", zipcode: "324" },
        { area: "龍潭區", zipcode: "325" },
        { area: "楊梅區", zipcode: "326" },
        { area: "新屋區", zipcode: "327" },
        { area: "觀音區", zipcode: "328" },
        { area: "桃園區", zipcode: "330" },
        { area: "龜山區", zipcode: "333" },
        { area: "八德區", zipcode: "334" },
        { area: "大溪區", zipcode: "335" },
        { area: "復興區", zipcode: "336" },
        { area: "大園區", zipcode: "337" },
        { area: "蘆竹區", zipcode: "338" },
      ],
    },
    {
      city: "台中市",
      areas: [
        { area: "中區", zipcode: "400" },
        { area: "東區", zipcode: "401" },
        { area: "南區", zipcode: "402" },
        { area: "西區", zipcode: "403" },
        { area: "北區", zipcode: "404" },
        { area: "北屯區", zipcode: "406" },
        { area: "西屯區", zipcode: "407" },
        { area: "南屯區", zipcode: "408" },
        { area: "太平區", zipcode: "411" },
        { area: "大里區", zipcode: "412" },
        { area: "霧峰區", zipcode: "413" },
        { area: "烏日區", zipcode: "414" },
        { area: "豐原區", zipcode: "420" },
        { area: "后里區", zipcode: "421" },
        { area: "石岡區", zipcode: "422" },
        { area: "東勢區", zipcode: "423" },
        { area: "和平區", zipcode: "424" },
        { area: "新社區", zipcode: "426" },
        { area: "潭子區", zipcode: "427" },
        { area: "大雅區", zipcode: "428" },
        { area: "神岡區", zipcode: "429" },
        { area: "大肚區", zipcode: "432" },
        { area: "沙鹿區", zipcode: "433" },
        { area: "龍井區", zipcode: "434" },
        { area: "梧棲區", zipcode: "435" },
        { area: "清水區", zipcode: "436" },
        { area: "大甲區", zipcode: "437" },
        { area: "外埔區", zipcode: "438" },
        { area: "大安區", zipcode: "439" },
      ],
    },
    {
      city: "台南市",
      areas: [
        { area: "中西區", zipcode: "700" },
        { area: "東區", zipcode: "701" },
        { area: "南區", zipcode: "702" },
        { area: "北區", zipcode: "704" },
        { area: "安平區", zipcode: "708" },
        { area: "安南區", zipcode: "709" },
        { area: "永康區", zipcode: "710" },
        { area: "歸仁區", zipcode: "711" },
        { area: "新化區", zipcode: "712" },
        { area: "左鎮區", zipcode: "713" },
        { area: "玉井區", zipcode: "714" },
        { area: "楠西區", zipcode: "715" },
        { area: "南化區", zipcode: "716" },
        { area: "仁德區", zipcode: "717" },
        { area: "關廟區", zipcode: "718" },
        { area: "龍崎區", zipcode: "719" },
        { area: "官田區", zipcode: "720" },
        { area: "麻豆區", zipcode: "721" },
        { area: "佳里區", zipcode: "722" },
        { area: "西港區", zipcode: "723" },
        { area: "七股區", zipcode: "724" },
        { area: "將軍區", zipcode: "725" },
        { area: "學甲區", zipcode: "726" },
        { area: "北門區", zipcode: "727" },
        { area: "新營區", zipcode: "730" },
        { area: "後壁區", zipcode: "731" },
        { area: "白河區", zipcode: "732" },
        { area: "東山區", zipcode: "733" },
        { area: "六甲區", zipcode: "734" },
        { area: "下營區", zipcode: "735" },
        { area: "柳營區", zipcode: "736" },
        { area: "鹽水區", zipcode: "737" },
        { area: "善化區", zipcode: "741" },
        { area: "大內區", zipcode: "742" },
        { area: "山上區", zipcode: "743" },
        { area: "新市區", zipcode: "744" },
        { area: "安定區", zipcode: "745" },
      ],
    },
    {
      city: "高雄市",
      areas: [
        { area: "新興區", zipcode: "800" },
        { area: "前金區", zipcode: "801" },
        { area: "苓雅區", zipcode: "802" },
        { area: "鹽埕區", zipcode: "803" },
        { area: "鼓山區", zipcode: "804" },
        { area: "旗津區", zipcode: "805" },
        { area: "前鎮區", zipcode: "806" },
        { area: "三民區", zipcode: "807" },
        { area: "楠梓區", zipcode: "811" },
        { area: "小港區", zipcode: "812" },
        { area: "左營區", zipcode: "813" },
        { area: "仁武區", zipcode: "814" },
        { area: "大社區", zipcode: "815" },
        { area: "岡山區", zipcode: "820" },
        { area: "路竹區", zipcode: "821" },
        { area: "阿蓮區", zipcode: "822" },
        { area: "田寮區", zipcode: "823" },
        { area: "燕巢區", zipcode: "824" },
        { area: "橋頭區", zipcode: "825" },
        { area: "梓官區", zipcode: "826" },
        { area: "彌陀區", zipcode: "827" },
        { area: "永安區", zipcode: "828" },
        { area: "湖內區", zipcode: "829" },
        { area: "鳳山區", zipcode: "830" },
        { area: "大寮區", zipcode: "831" },
        { area: "林園區", zipcode: "832" },
        { area: "鳥松區", zipcode: "833" },
        { area: "大樹區", zipcode: "840" },
        { area: "旗山區", zipcode: "842" },
        { area: "美濃區", zipcode: "843" },
        { area: "六龜區", zipcode: "844" },
        { area: "甲仙區", zipcode: "845" },
        { area: "杉林區", zipcode: "846" },
        { area: "內門區", zipcode: "847" },
        { area: "茂林區", zipcode: "851" },
        { area: "桃源區", zipcode: "852" },
        { area: "那瑪夏區", zipcode: "853" },
      ],
    },

    {
      city: "基隆市",
      areas: [
        { area: "仁愛區", zipcode: "200" },
        { area: "信義區", zipcode: "201" },
        { area: "中正區", zipcode: "202" },
        { area: "中山區", zipcode: "203" },
        { area: "安樂區", zipcode: "204" },
        { area: "暖暖區", zipcode: "205" },
        { area: "七堵區", zipcode: "206" },
      ],
    },
    {
      city: "宜蘭縣",
      areas: [
        { area: "宜蘭市", zipcode: "260" },
        { area: "頭城鎮", zipcode: "261" },
        { area: "礁溪鄉", zipcode: "262" },
        { area: "壯圍鄉", zipcode: "263" },
        { area: "員山鄉", zipcode: "264" },
        { area: "羅東鎮", zipcode: "265" },
        { area: "三星鄉", zipcode: "266" },
        { area: "大同鄉", zipcode: "267" },
        { area: "五結鄉", zipcode: "268" },
        { area: "冬山鄉", zipcode: "269" },
        { area: "蘇澳鎮", zipcode: "270" },
        { area: "南澳鄉", zipcode: "272" },
        { area: "釣魚台列嶼", zipcode: "290" },
      ],
    },
    {
      city: "新竹縣",
      areas: [
        { area: "竹北市", zipcode: "302" },
        { area: "湖口鄉", zipcode: "303" },
        { area: "新豐鄉", zipcode: "304" },
        { area: "新埔鎮", zipcode: "305" },
        { area: "關西鎮", zipcode: "306" },
        { area: "芎林鄉", zipcode: "307" },
        { area: "寶山鄉", zipcode: "308" },
        { area: "竹東鎮", zipcode: "310" },
        { area: "五峰鄉", zipcode: "311" },
        { area: "橫山鄉", zipcode: "312" },
        { area: "尖石鄉", zipcode: "313" },
        { area: "北埔鄉", zipcode: "314" },
        { area: "峨眉鄉", zipcode: "315" },
      ],
    },
    {
      city: "苗栗縣",
      areas: [
        { area: "苗栗市", zipcode: "360" },
        { area: "苑裡鎮", zipcode: "358" },
        { area: "通霄鎮", zipcode: "357" },
        { area: "竹南鎮", zipcode: "350" },
        { area: "頭份市", zipcode: "351" },
        { area: "後龍鎮", zipcode: "356" },
        { area: "卓蘭鎮", zipcode: "369" },
        { area: "大湖鄉", zipcode: "364" },
        { area: "公館鄉", zipcode: "363" },
        { area: "銅鑼鄉", zipcode: "366" },
        { area: "三義鄉", zipcode: "367" },
        { area: "造橋鄉", zipcode: "361" },
        { area: "三灣鄉", zipcode: "352" },
        { area: "獅潭鄉", zipcode: "354" },
        { area: "南庄鄉", zipcode: "353" },
        { area: "泰安鄉", zipcode: "365" },
      ],
    },
    {
      city: "彰化縣",
      areas: [
        { area: "彰化市", zipcode: "500" },
        { area: "鹿港鎮", zipcode: "505" },
        { area: "和美鎮", zipcode: "508" },
        { area: "員林市", zipcode: "510" },
        { area: "溪湖鎮", zipcode: "514" },
        { area: "田中鎮", zipcode: "520" },
        { area: "北斗鎮", zipcode: "521" },
        { area: "二林鎮", zipcode: "526" },
        { area: "線西鄉", zipcode: "507" },
        { area: "伸港鄉", zipcode: "509" },
        { area: "福興鄉", zipcode: "506" },
        { area: "秀水鄉", zipcode: "504" },
        { area: "花壇鄉", zipcode: "503" },
        { area: "芬園鄉", zipcode: "502" },
        { area: "大村鄉", zipcode: "515" },
        { area: "埔鹽鄉", zipcode: "516" },
        { area: "埔心鄉", zipcode: "513" },
        { area: "永靖鄉", zipcode: "512" },
        { area: "社頭鄉", zipcode: "511" },
        { area: "田尾鄉", zipcode: "522" },
        { area: "埤頭鄉", zipcode: "523" },
        { area: "溪州鄉", zipcode: "524" },
        { area: "竹塘鄉", zipcode: "525" },
        { area: "大城鄉", zipcode: "527" },
        { area: "芳苑鄉", zipcode: "528" },
        { area: "二水鄉", zipcode: "530" },
      ],
    },
    {
      city: "南投縣",
      areas: [
        { area: "南投市", zipcode: "540" },
        { area: "埔里鎮", zipcode: "545" },
        { area: "草屯鎮", zipcode: "542" },
        { area: "竹山鎮", zipcode: "557" },
        { area: "集集鎮", zipcode: "552" },
        { area: "名間鄉", zipcode: "551" },
        { area: "鹿谷鄉", zipcode: "558" },
        { area: "魚池鄉", zipcode: "555" },
        { area: "信義鄉", zipcode: "556" },
        { area: "國姓鄉", zipcode: "544" },
        { area: "仁愛鄉", zipcode: "546" },
        { area: "水里鄉", zipcode: "553" },
      ],
    },
    {
      city: "屏東縣",
      areas: [
        { area: "屏東市", zipcode: "900" },
        { area: "潮州鎮", zipcode: "920" },
        { area: "東港鎮", zipcode: "928" },
        { area: "恆春鎮", zipcode: "946" },
        { area: "萬丹鄉", zipcode: "913" },
        { area: "長治鄉", zipcode: "908" },
        { area: "麟洛鄉", zipcode: "909" },
        { area: "九如鄉", zipcode: "904" },
        { area: "里港鄉", zipcode: "905" },
        { area: "鹽埔鄉", zipcode: "907" },
        { area: "內埔鄉", zipcode: "912" },
        { area: "萬巒鄉", zipcode: "923" },
        { area: "新園鄉", zipcode: "932" },
        { area: "枋寮鄉", zipcode: "940" },
        { area: "三地門鄉", zipcode: "901" },
        { area: "霧台鄉", zipcode: "902" },
        { area: "瑪家鄉", zipcode: "903" },
        { area: "泰武鄉", zipcode: "921" },
        { area: "來義鄉", zipcode: "922" },
        { area: "春日鄉", zipcode: "942" },
        { area: "獅子鄉", zipcode: "943" },
        { area: "車城鄉", zipcode: "944" },
        { area: "滿州鄉", zipcode: "947" },
        { area: "枋山鄉", zipcode: "941" },
      ],
    },
    {
      city: "花蓮縣",
      areas: [
        { area: "花蓮市", zipcode: "970" },
        { area: "新城鄉", zipcode: "971" },
        { area: "秀林鄉", zipcode: "972" },
        { area: "吉安鄉", zipcode: "973" },
        { area: "壽豐鄉", zipcode: "974" },
        { area: "鳳林鎮", zipcode: "975" },
        { area: "光復鄉", zipcode: "976" },
        { area: "豐濱鄉", zipcode: "977" },
        { area: "瑞穗鄉", zipcode: "978" },
        { area: "萬榮鄉", zipcode: "979" },
        { area: "玉里鎮", zipcode: "981" },
        { area: "卓溪鄉", zipcode: "982" },
        { area: "富里鄉", zipcode: "983" },
      ],
    },
    {
      city: "台東縣",
      areas: [
        { area: "台東市", zipcode: "950" },
        { area: "成功鎮", zipcode: "961" },
        { area: "關山鎮", zipcode: "956" },
        { area: "長濱鄉", zipcode: "962" },
        { area: "池上鄉", zipcode: "958" },
        { area: "東河鄉", zipcode: "959" },
        { area: "鹿野鄉", zipcode: "955" },
        { area: "卑南鄉", zipcode: "954" },
        { area: "大武鄉", zipcode: "965" },
        { area: "綠島鄉", zipcode: "951" },
        { area: "達仁鄉", zipcode: "966" },
        { area: "太麻里鄉", zipcode: "963" },
        { area: "延平鄉", zipcode: "953" },
        { area: "海端鄉", zipcode: "957" },
        { area: "金峰鄉", zipcode: "964" },
        { area: "蘭嶼鄉", zipcode: "952" },
      ],
    },
    {
      city: "澎湖縣",
      areas: [
        { area: "馬公市", zipcode: "880" },
        { area: "西嶼鄉", zipcode: "881" },
        { area: "望安鄉", zipcode: "882" },
        { area: "七美鄉", zipcode: "883" },
        { area: "白沙鄉", zipcode: "884" },
        { area: "湖西鄉", zipcode: "885" },
      ],
    },
    {
      city: "金門縣",
      areas: [
        { area: "金城鎮", zipcode: "890" },
        { area: "金沙鎮", zipcode: "891" },
        { area: "金湖鎮", zipcode: "892" },
        { area: "金寧鄉", zipcode: "893" },
        { area: "烈嶼鄉", zipcode: "894" },
        { area: "烏坵鄉", zipcode: "896" },
      ],
    },
    {
      city: "連江縣",
      areas: [
        { area: "南竿鄉", zipcode: "209" },
        { area: "北竿鄉", zipcode: "210" },
        { area: "莒光鄉", zipcode: "211" },
        { area: "東引鄉", zipcode: "212" },
      ],
    },
  ]);
  return { cityArea };
};
